services:
  name-generator_client:
    container_name: name-generator_client
    build: .
    # image: chiefmikey/name-generator:latest
    depends_on:
      name-generator_db:
        condition: service_healthy
    env_file:
      - .env
    networks:
      - ng-network
    ports:
      - 80:3001

  # name-generator_db:
  #   container_name: name-generator_db
  #   image: chiefmikey/cassandra:latest
  #   networks:
  #     - ng-network
  #   volumes:
  #     - cassandra-data:/var/lib/cassandra
  #   healthcheck:
  #     test:
  #       cd /opt/cassandra && su -s /bin/bash -c 'bin/cqlsh --debug' cassandra
  #     interval: 10s
  #     timeout: 10s
  #     retries: 10

  name-generator_db:
    container_name: name-generator_db
    image: mongo:latest
    networks:
      - ng-network
    volumes:
      - mongo-data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=namegenerator
    ports:
      - 27017:27017
    healthcheck:
      test:
        echo 'db.runCommand("ping").ok' | mongo localhost:27017/namegenerator
        --quiet
      interval: 10s
      timeout: 10s
      retries: 10

volumes:
  mongo-data:
  # cassandra-data:

networks:
  ng-network:
