services:
  ng_client:
    build: .
    depends_on:
      ng_db:
        condition: service_healthy
    env_file:
      - .env
    networks:
      - ng-network
    ports:
      - '80:8080'

  ng_db:
    image: cassandra:latest
    networks:
      - ng-network
    ports:
      - '9042:9042'
    volumes:
      - cassandra-data:/var/lib/cassandra
    healthcheck:
      test: cqlsh --debug
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  cassandra-data:

networks:
  ng-network:
